
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcwxrstpugjwuapsemcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpjd3hyc3RwdWdqd3VhcHNlbWN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzOTI4MzgsImV4cCI6MjA1Nzk2ODgzOH0.61xL3dMKhmS4QfdhZZzPzI6hT7ASWtyEkAPGpLhGU7E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
